name: Build ai-assistant

on:
  push:
    branches:
      - main
    paths:
      - 'ai-assistant/**'
      - '.github/workflows/build-ai-assistant.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'ai-assistant/**'
      - '.github/workflows/build-ai-assistant.yml'

jobs:
  build-ai-assistant:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - uses: 'google-github-actions/auth@v3'
      id: auth
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      with:
        token_format: access_token
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - uses: docker/login-action@v4
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Build And Push ai-assistant image
      uses: docker/build-push-action@v7
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      with:
        context: ./ai-assistant/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/images/ai-assistant:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build ai-assistant image
      uses: docker/build-push-action@v7
      if: ${{ !(github.ref == 'refs/heads/main' && github.event_name != 'pull_request') }}
      with:
        context: ./ai-assistant/
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
